name: Hadolint

on:
  workflow_dispatch: # Allow manual runs.
  pull_request:
    branches: [ 'main' ]

jobs:
  dockerfile-lint:
    name: Dockerfile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning
